GET http://localhost:5185/games

###
GET http://localhost:5185/games/2

###
GET http://localhost:5185/games/100

###
POST http://localhost:5185/games
Content-Type: application/json

{
    "name": "Dragon Questors",
    "genreId": 2,
    "price": 420000,
    "releaseDate" : "2024-03-30"
}

###
PUT http://localhost:5185/games/1
Content-Type: application/json

{
    "name": "The Silent Code II",
    "genre": "Strategy",
    "price": 149000,
    "releaseDate": "2017-03-06"
}

###
PUT http://localhost:5185/games/100
Content-Type: application/json

{
    "name": "The Silent Code II",
    "genre": "Strategy",
    "price": 149000,
    "releaseDate": "2017-03-06"
}

###
DELETE  http://localhost:5185/games/1

###
DELETE  http://localhost:5185/games/1